language: php

php:
  - 7.0
  - 5.6
  - 5.5
  - 5.4
  - hhvm

before_script:
  - pip install --user codecov
  - composer self-update && composer install --dev
  - php -S localhost:8000 -t tests/analyze &

script:
  - ./vendor/bin/phpunit

after_success:
  - codecov
